apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ${name}
spec:
  template:
    metadata:
      labels:
        environment: ${name}
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: ${nodeclass_name}

      taints:
      - key: node-pool
        value: ${name}
        effect: NoSchedule

      requirements:
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values:
        - "t2.medium"

  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: Never

  #  limits:
  #    cpu: 12
  #    memory: 24Gi
