apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ${name}
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        Name: "${environment}-${name}-private-subnet"
        Karpenter: "${name}-*"

  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: ${cluster_name}
#%{~for sg in security_groups~}
    - name: ${sg}
#%{~endfor~}

  instanceProfile: "${instance_profile}"

  tags:
    owner: "${name}-karpenter"

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        deleteOnTermination: true
