apiVersion: v1
kind: Pod
metadata:
  name: arm
spec:
  containers:
  - image: nginx
    name: arm
    resources: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: environment
            operator: In
            values:
            - "alex-arm"
  tolerations:
  - effect: NoSchedule
    key: node-pool
    operator: Equal
    value: alex-arm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
