apiVersion: v1
kind: Pod
metadata:
  name: x86
spec:
  containers:
  - image: nginx
    name: x86
    resources:
      requests:
        memory: 200Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: environment
            operator: In
            values:
            - "alex-x86"
  tolerations:
  - effect: NoSchedule
    key: node-pool
    operator: Equal
    value: alex-x86
  dnsPolicy: ClusterFirst
  restartPolicy: Always
